language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

# TODO: also run checkbashisms.pl (currently two instances of non-compliance)
script:
 - ./ghcup.sh -v install 8.2.2
 - ./ghcup.sh -v install 8.4.3
 - ./ghcup.sh -v install 8.6.1
 - ./ghcup.sh -v set 8.6.1
 - ./ghcup.sh -v set 8.4.3
 - wget https://www.haskell.org/cabal/release/cabal-install-2.2.0.0/cabal-install-2.2.0.0-x86_64-unknown-linux.tar.gz
 - tar -xzf cabal-install-2.2.0.0-x86_64-unknown-linux.tar.gz
 - ./cabal new-update
 - ./cabal new-install ShellCheck
 - ~/.cabal/bin/shellcheck ghcup.sh

matrix:
  fast_finish: true
