language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

addons:
  apt:
    sources:
    - debian-buster    # Grab shellcheck from the Debian repo (o_O)
    packages:
    - shellcheck

# TODO: also run checkbashisms.pl (currently two instances of non-compliance)
script:
 - shellcheck ghcup.sh

matrix:
  fast_finish: true
