language: bash

# Use container-based infrastructure for quicker build start-up
sudo: false

# TODO: also run checkbashisms.pl (currently two instances of non-compliance)
script:
 - ./.travis.sh

matrix:
  fast_finish: true
